### ISSUE TITLE
Failing tests since short plugin name

### ISSUE THREAD

**Issue by danielcompton** [lambdaisland/kaocha#142]
Since https://github.com/lambdaisland/kaocha/commit/4bc0b901e7c30b6a1e09d0eeda854548507430f9, the tests have been failing.

I'm not sure quite how, but it looks like the command line args for `:kaocha.plugin/profiling` are included twice if you use the short version of the profiling plugin.

```clojure
 [nil
 "--[no-]profiling"
  "Show slowest tests of each type with timing information."]
 [nil
  "--profiling-count NUM"
  "Show this many slow tests of each kind in profile results."
  :parse-fn
```

This causes an exception in tools.cli:

```java
Exception in thread "main" java.lang.AssertionError: Assert failed: (distinct?* (remove nil? (map :long-opt %)))
	at clojure.tools.cli$compile_option_specs.invokeStatic(cli.cljc:282)
	at clojure.tools.cli$compile_option_specs.invoke(cli.cljc:282)
	at clojure.tools.cli$parse_opts.invokeStatic(cli.cljc:707)
	at clojure.tools.cli$parse_opts.doInvoke(cli.cljc:544)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at kaocha.runner$_main_STAR_.invokeStatic(runner.clj:157)
	at kaocha.runner$_main_STAR_.doInvoke(runner.clj:140)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at kaocha.runner$_main.invokeStatic(runner.clj:174)
	at kaocha.runner$_main.doInvoke(runner.clj:172)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
```

The minimal diff to make the tests pass is:

```diff
diff --git a/tests.edn b/tests.edn
index 379bed6..9050176 100644
--- a/tests.edn
+++ b/tests.edn
@@ -1,5 +1,5 @@
 #kaocha/v1
-{:plugins [:kaocha.plugin.alpha/info :profiling :print-invocations :hooks :notifier]
+{:plugins [:kaocha.plugin.alpha/info :kaocha.plugin/profiling :print-invocations :hooks :notifier]

  :tests   [{:id         :unit
             :test-paths ["test/shared"
```

**Comment by danielcompton** [comment]
I think this was fixed by #143.
