### ISSUE TITLE
Cannot Locate Kaocha/Runner

### ISSUE THREAD

**Issue by ThompsonJonM** [lambdaisland/kaocha#21]
I'm looking to see about introducing Kaocha/Cucumber/Selenium to my workspace as my new development team writes in Clojure. I would like to see homogenizing the languages we use for testing (currently Ruby/Cucumber/Watir) for this team as they are not very familiar with Ruby and I would be the only individual maintaining it. Unfortunately, it appears that the way in which I installed kaocha could have been problematic. I am receiving the following stack trace:

`Exception in thread "main" java.io.FileNotFoundException: Could not locate kaocha/runner__init.class, kaocha/runner.clj or kaocha/runner.cljc on classpath.
at clojure.lang.RT.load(RT.java:466)
        at clojure.lang.RT.load(RT.java:428)
        at clojure.core$load$fn__6824.invoke(core.clj:6126)
        at clojure.core$load.invokeStatic(core.clj:6125)
        at clojure.core$load.doInvoke(core.clj:6109)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5908)
        at clojure.core$load_one.invoke(core.clj:5903)
        at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
        at clojure.core$load_lib.invokeStatic(core.clj:5947)
        at clojure.core$load_lib.doInvoke(core.clj:5928)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$load_libs.invokeStatic(core.clj:5985)
        at clojure.core$load_libs.doInvoke(core.clj:5969)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$require.invokeStatic(core.clj:6007)
        at clojure.main$main_opt.invokeStatic(main.clj:491)
        at clojure.main$main_opt.invoke(main.clj:487)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
`

I followed the steps from the installation section of the Readme and cannot determine where exactly this could be popping up. Any assistance is more than appreciated!

**Comment by ThompsonJonM** [comment]
Determined that this was caused by a missing dependency. Oops!

**Comment by plexus** [comment]
Thank you for trying out Kaocha. Don't hesitate to open an issue if you run into any more problems.
