### ISSUE TITLE
Watch feature errors out when reloading ns

### ISSUE THREAD

**Issue by phillipm** [lambdaisland/kaocha#5]
When I enable `watch` and save a file, `kaocha` shows the following stacktrace

```
java.io.FileNotFoundException: /home/mates/dev/matcher-combinators/test/matcher_combinators/4913 (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at clojure.java.io$fn__11162.invokeStatic(io.clj:229)
	at clojure.java.io$fn__11162.invoke(io.clj:229)
	at clojure.java.io$fn__11075$G__11068__11082.invoke(io.clj:69)
	at clojure.java.io$fn__11136.invokeStatic(io.clj:165)
	at clojure.java.io$fn__11136.invoke(io.clj:165)
	at clojure.java.io$fn__11088$G__11064__11095.invoke(io.clj:69)
	at clojure.java.io$reader.invokeStatic(io.clj:102)
	at clojure.java.io$reader.doInvoke(io.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.tools.namespace.file$read_file_ns_decl.invokeStatic(file.clj:24)
	at clojure.tools.namespace.file$read_file_ns_decl.invoke(file.clj:17)
	at clojure.tools.namespace.file$read_file_ns_decl.invokeStatic(file.clj:22)
	at clojure.tools.namespace.file$read_file_ns_decl.invoke(file.clj:17)
	at kaocha.watch$reload_file_BANG_.invokeStatic(watch.clj:20)
	at kaocha.watch$reload_file_BANG_.invoke(watch.clj:18)
	at clojure.core$run_BANG_$fn__8544.invoke(core.clj:7660)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__7952.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__7952.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__7894$G__7889__7907.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6773)
	at clojure.core$run_BANG_.invokeStatic(core.clj:7655)
	at clojure.core$run_BANG_.invoke(core.clj:7655)
	at kaocha.watch$run$fn__12098.invoke(watch.clj:53)
	at clojure.core$binding_conveyor_fn$fn__5575.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by plexus** [comment]
Is this on the matcher-combinators repo? Would it be possible to set up a repo that I can clone that reproduces this?

**Comment by phillipm** [comment]
Yeah, I've uploaded the branch https://github.com/nubank/matcher-combinators/tree/pm/trying-out-kaocha

**Comment by phillipm** [comment]
I noticed that you don't use `clojure/tools.namespace` for reloading namespaces.
Not doing this in Midje has caused a fair number of issues with the autoloader ([this issue](https://github.com/marick/Midje/issues/288), [and this PR](https://github.com/marick/Midje/pull/410)). The PR I never finished because I ran into strange issues when trying to use `tools.namespace`'s reloading code from within the codebase (potentially something to do with testing midje with midje). I think it might be easier if the autoloader is external to the actual test framework, like in https://github.com/jakemcc/lein-test-refresh, which is a good place to see how `clojure/tools.namespace` can be wired up.

Anyways, I'd suggest looking out for reload issues like removing variables that are no longer defined and reloading protocols, both of which are addressed within `clojure/tools.namespace`

**Comment by lambdaisland** [comment]
Kaocha uses tools.namespace now for the tracking and reloading.

**Comment by phillipm** [comment]
Very cool!

Wanted to drop a data point as you are adding features to the auto test loading:
Often I launch midje autotest runner after making some changes to discover that I have an import error or something. When this happens I wait a long time for everything to spin up and then the broken namespace crashes everything. While this could be fixed by me doing dev in a more repl-driven way, I still think it is valid to take into account.
So if there is some crazy way to recover from errors while loading a namespace, that would be amazing! Maybe pause the namespace loader and allow you to resume loading after fixing the typo?

cheers!

**Comment by plexus** [comment]
To an extent this might already work. What happens currently during the load stage is that when it tries to load namespace `foo.bar-test` and that fails, then it prints a warning, marks the namespace as being a failing test, and continues with the rest. Next time the watcher kicks in it'll try that again until it manages to load.

The current approach still does have some issues, in particular I'd like to make a distinction between a load error in the test namespace itself, and a load error in one of its dependencies. The former can be considered a failure/error, the latter is a more fundamental problem and probably means its not meaningful to try to run tests at all.
